[package]
name = 'osinfo'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'osinfo'

[dependencies]
extendr-api = '*'
os_info = { version = "3", default-features = false }
