# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_osinfo_wrappers", use_symbols = TRUE, package_name = "osinfo")

#' @docType package
#' @usage NULL
#' @useDynLib osinfo, .registration = TRUE
NULL

#' get os information
os_info_impl <- function() .Call(wrap__os_info_impl)


# nolint end
